### ISSUE TITLE
[MRA] Md5 issue (present in Other zip and official full set)

### ISSUE THREAD

**Issue by wwark** [eubrunosilva/MiSTerMRA#1]
Other:
Donkey Kong Jr. (Japan).mra 

Official fullset:
Bagman
Botanic (English - spanish, set 1)
Pickin'
Squash (Itisa)

Thanks !

**Comment by eubrunosilva** [comment]
hi. thanks.

i just changed the checking routine (didnt had yet the repeat, offset, length) and will simulate the creation of the rom in mister and check md5 

In the next couple of days i will release an update.

**Comment by eubrunosilva** [comment]
hi check new packs. thanks

**Comment by wwark** [comment]
Fixed thank you !
